// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosshafContextHandeling.MainModels.NewModels;

#nullable disable

namespace MosshafContextHandeling.MainModels.Migrations
{
    [DbContext(typeof(Quran_quran4Context))]
    [Migration("20251215171534_addMultiMediaLecturerAndItems")]
    partial class addMultiMediaLecturerAndItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("HezbNo")
                        .HasColumnType("int");

                    b.Property<string>("ImgWarsh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<int?>("PartNo")
                        .HasColumnType("int");

                    b.Property<int?>("RobeeNo")
                        .HasColumnType("int");

                    b.Property<string>("SearchAyaa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Verse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerseNo")
                        .HasColumnType("int");

                    b.Property<string>("VerseNoAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerseNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("MultimediaCategories");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MultimediaCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MultimediaLecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfViews")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MultimediaCategoryId");

                    b.HasIndex("MultimediaLecturerId");

                    b.ToTable("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("MultimediaLecturers");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Fadl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mwadee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NoOfVerses")
                        .HasColumnType("int");

                    b.Property<string>("SabbNzol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SabbTasmia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taareef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Sura", "Sura")
                        .WithMany("Ayas")
                        .HasForeignKey("SuraId");

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", "MultimediaCategory")
                        .WithMany("MultimediaItems")
                        .HasForeignKey("MultimediaCategoryId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", "MultimediaLecturer")
                        .WithMany()
                        .HasForeignKey("MultimediaLecturerId");

                    b.Navigation("MultimediaCategory");

                    b.Navigation("MultimediaLecturer");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Navigation("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Navigation("Ayas");
                });
#pragma warning restore 612, 618
        }
    }
}
