// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosshafContextHandeling.MainModels.NewModels;

#nullable disable

namespace MosshafContextHandeling.MainModels.Migrations
{
    [DbContext(typeof(Quran_quran4Context))]
    [Migration("20251216090222_addRecitersTable")]
    partial class addRecitersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Ahkam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Araby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Gahdamy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gasas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kiaharsy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaylMaram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rwaee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("Ahkams");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AhkamBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AhkamBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Eegab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Esteaab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lebab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moharrer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mosnad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("AsbabNozools");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozoolBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AsbabNozoolBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("HezbNo")
                        .HasColumnType("int");

                    b.Property<string>("ImgWarsh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<int?>("PartNo")
                        .HasColumnType("int");

                    b.Property<int?>("RobeeNo")
                        .HasColumnType("int");

                    b.Property<string>("SearchAyaa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Verse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerseNo")
                        .HasColumnType("int");

                    b.Property<string>("VerseNoAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerseNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Erab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Daas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Darwish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gadwal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kharat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nahas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tbian")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("Erabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.ErabBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErabBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Keraat", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Keraats");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Maany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaanyBookId")
                        .HasColumnType("int");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaanyBookId");

                    b.ToTable("Maanies");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MaanyBookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaanyBookId");

                    b.ToTable("MaanyBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("MultimediaCategories");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MultimediaCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MultimediaLecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfViews")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MultimediaCategoryId");

                    b.HasIndex("MultimediaLecturerId");

                    b.ToTable("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("MultimediaLecturers");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Reciter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeraatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KeraatId");

                    b.ToTable("Reciters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Fadl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mwadee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NoOfVerses")
                        .HasColumnType("int");

                    b.Property<string>("SabbNzol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SabbTasmia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taareef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Ahkam", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId");

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozool", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Sura", "Sura")
                        .WithMany("Ayas")
                        .HasForeignKey("SuraId");

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Erab", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Maany", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MaanyBook", "MaanyBook")
                        .WithMany()
                        .HasForeignKey("MaanyBookId");

                    b.Navigation("MaanyBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MaanyBook", null)
                        .WithMany("MaanyBooks")
                        .HasForeignKey("MaanyBookId");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", "MultimediaCategory")
                        .WithMany("MultimediaItems")
                        .HasForeignKey("MultimediaCategoryId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", "MultimediaLecturer")
                        .WithMany()
                        .HasForeignKey("MultimediaLecturerId");

                    b.Navigation("MultimediaCategory");

                    b.Navigation("MultimediaLecturer");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Reciter", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Keraat", "Keraat")
                        .WithMany()
                        .HasForeignKey("KeraatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keraat");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.Navigation("MaanyBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Navigation("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Navigation("Ayas");
                });
#pragma warning restore 612, 618
        }
    }
}
