// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MosshafContextHandeling.MainModels.NewModels;

#nullable disable

namespace MosshafContextHandeling.MainModels.Migrations
{
    [DbContext(typeof(Quran_quran4Context))]
    [Migration("20251228123931_removeOldTablesAfterRestructure")]
    partial class removeOldTablesAfterRestructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Ahhkam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AhkamBookId")
                        .HasColumnType("int");

                    b.Property<int?>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AhkamBookId");

                    b.HasIndex("AyaId");

                    b.ToTable("Ahhkams");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AhkamBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AhkamBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozoolBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AsbabNozoolBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozoolNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsbabNozoolBookId")
                        .HasColumnType("int");

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsbabNozoolBookId");

                    b.HasIndex("AyaId");

                    b.ToTable("AsbabNozoolsNew");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BeginningLetterId")
                        .HasColumnType("int");

                    b.Property<int?>("HezbNo")
                        .HasColumnType("int");

                    b.Property<string>("ImgWarsh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<int?>("PartNo")
                        .HasColumnType("int");

                    b.Property<int?>("RobeeNo")
                        .HasColumnType("int");

                    b.Property<string>("Sound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Verse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VerseNo")
                        .HasColumnType("int");

                    b.Property<string>("VerseNoAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerseNoSign")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Egaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BabId")
                        .HasColumnType("int");

                    b.Property<string>("Matn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BabId");

                    b.ToTable("Egazs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.EgazBab", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BabNo")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("EgazBookNo")
                        .HasColumnType("int");

                    b.Property<int>("EgazChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ParentId");

                    b.ToTable("EgazBabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.EgazBook", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EgazBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.EgazChapter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("EgazBookId")
                        .HasColumnType("int");

                    b.Property<int>("EgazChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EgazBookId");

                    b.ToTable("EgazChapters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Erab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Daas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Darwish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gadwal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kharat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nahas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tbian")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("Erabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.ErabBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErabBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Keraat", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Keraats");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Maany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaanyBookId")
                        .HasColumnType("int");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaanyBookId");

                    b.ToTable("Maanies");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("MaanyBookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaanyBookId");

                    b.ToTable("MaanyBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Mogam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MogamBabId")
                        .HasColumnType("int");

                    b.Property<int?>("MogamBabNo")
                        .HasColumnType("int");

                    b.Property<int?>("MogamBookNo")
                        .HasColumnType("int");

                    b.Property<int?>("MogamChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Nass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MogamBabId");

                    b.ToTable("Mogams");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamBab", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MogamChapterId")
                        .HasColumnType("int");

                    b.Property<int>("MogamChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MogamChapterId");

                    b.ToTable("MogamBabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamBook", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MogamBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamChapter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<int>("MogamBookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MogamBookId");

                    b.ToTable("MogamChapters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Moshabeh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Moshabehs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("MultimediaCategories");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MultimediaCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MultimediaLecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfViews")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MultimediaCategoryId");

                    b.HasIndex("MultimediaLecturerId");

                    b.ToTable("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("MultimediaLecturers");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Olom", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("BabId")
                        .HasColumnType("int");

                    b.Property<int?>("BabNo")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Matn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OlomBookNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubBabNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BabId");

                    b.ToTable("Oloms");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomBab", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BabNo")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ParentId");

                    b.ToTable("OlomBabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomBook", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MappedColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OlomBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomChapter", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OlomBookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OlomBookId");

                    b.ToTable("OlomChapters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Radio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Radios");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Reciter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeraatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KeraatId");

                    b.ToTable("Reciters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Fadl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mwadee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NoOfVerses")
                        .HasColumnType("int");

                    b.Property<string>("SabbNzol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SabbTasmia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taareef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TafseerBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TafseerBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TafseerNabawy", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("BookName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HadithSearch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadithTxt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Selid")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Taraf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerseNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("TafseerNabawies");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Tafser", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AyaId")
                        .HasColumnType("int");

                    b.Property<int?>("TafseerBookId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.HasIndex("TafseerBookId");

                    b.ToTable("Tafsers");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Tagwed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Gverse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagweed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("Tagweds");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TragemBook", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MappedColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TragemBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TragemNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TragemBookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.HasIndex("TragemBookId");

                    b.ToTable("TragemsNew");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Ahhkam", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.AhkamBook", "AhkamBook")
                        .WithMany()
                        .HasForeignKey("AhkamBookId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId");

                    b.Navigation("AhkamBook");

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.AsbabNozoolNew", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.AsbabNozoolBook", "AsbabNozoolBook")
                        .WithMany()
                        .HasForeignKey("AsbabNozoolBookId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsbabNozoolBook");

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Aya", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Sura", "Sura")
                        .WithMany("Ayas")
                        .HasForeignKey("SuraId");

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Egaz", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.EgazBab", "Bab")
                        .WithMany()
                        .HasForeignKey("BabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bab");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.EgazBab", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.EgazChapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.EgazBab", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Chapter");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.EgazChapter", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.EgazBook", "EgazBook")
                        .WithMany()
                        .HasForeignKey("EgazBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EgazBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Erab", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Maany", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MaanyBook", "MaanyBook")
                        .WithMany()
                        .HasForeignKey("MaanyBookId");

                    b.Navigation("MaanyBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MaanyBook", null)
                        .WithMany("MaanyBooks")
                        .HasForeignKey("MaanyBookId");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Mogam", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MogamBab", "MogamBab")
                        .WithMany("Mogams")
                        .HasForeignKey("MogamBabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MogamBab");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamBab", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MogamChapter", "Chapter")
                        .WithMany("MogamBabs")
                        .HasForeignKey("MogamChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamChapter", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MogamBook", "MogamBook")
                        .WithMany("MogamChapters")
                        .HasForeignKey("MogamBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MogamBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaItem", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", "MultimediaCategory")
                        .WithMany("MultimediaItems")
                        .HasForeignKey("MultimediaCategoryId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.MultimediaLecturer", "MultimediaLecturer")
                        .WithMany()
                        .HasForeignKey("MultimediaLecturerId");

                    b.Navigation("MultimediaCategory");

                    b.Navigation("MultimediaLecturer");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Olom", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.OlomBab", "Bab")
                        .WithMany("Oloms")
                        .HasForeignKey("BabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bab");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomBab", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.OlomChapter", "Chapter")
                        .WithMany("OlomBabs")
                        .HasForeignKey("ChapterId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.OlomBab", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Chapter");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomChapter", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.OlomBook", "OlomBook")
                        .WithMany("Chapters")
                        .HasForeignKey("OlomBookId");

                    b.Navigation("OlomBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Reciter", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Keraat", "Keraat")
                        .WithMany()
                        .HasForeignKey("KeraatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keraat");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TafseerNabawy", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Sura", "Sura")
                        .WithMany()
                        .HasForeignKey("SuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Tafser", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId");

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.TafseerBook", "TafseerBook")
                        .WithMany()
                        .HasForeignKey("TafseerBookId");

                    b.Navigation("Aya");

                    b.Navigation("TafseerBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Tagwed", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.TragemNew", b =>
                {
                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MosshafContextHandeling.MainModels.NewModels.TragemBook", "TragemBook")
                        .WithMany()
                        .HasForeignKey("TragemBookId");

                    b.Navigation("Aya");

                    b.Navigation("TragemBook");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MaanyBook", b =>
                {
                    b.Navigation("MaanyBooks");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamBab", b =>
                {
                    b.Navigation("Mogams");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamBook", b =>
                {
                    b.Navigation("MogamChapters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MogamChapter", b =>
                {
                    b.Navigation("MogamBabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.MultimediaCategory", b =>
                {
                    b.Navigation("MultimediaItems");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomBab", b =>
                {
                    b.Navigation("Oloms");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomBook", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.OlomChapter", b =>
                {
                    b.Navigation("OlomBabs");
                });

            modelBuilder.Entity("MosshafContextHandeling.MainModels.NewModels.Sura", b =>
                {
                    b.Navigation("Ayas");
                });
#pragma warning restore 612, 618
        }
    }
}
