// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("3egab", Schema = "quran_quran2")]
public partial class _3egab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nass")]
    public string Nass { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("pageid")]
    public int Pageid { get; set; }
}