// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("a7kam", Schema = "quran_quran2")]
public partial class A7kam
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [Column("GVerse")]
    public string Gverse { get; set; }

    public string Meaning1 { get; set; }

    public string Meaning2 { get; set; }

    public string English { get; set; }

    public string Germany { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    [Column("tabary")]
    public string Tabary { get; set; }

    [Column("kortoby")]
    public string Kortoby { get; set; }

    [Column("safwa")]
    public string Safwa { get; set; }

    [Column("ibnkathir")]
    public string Ibnkathir { get; set; }

    [Column("kashaf")]
    public string Kashaf { get; set; }

    [Column("zelal")]
    public string Zelal { get; set; }

    [Column("sa3dy")]
    public string Sa3dy { get; set; }

    [Column("kadeer")]
    public string Kadeer { get; set; }

    [Column("wa7dy")]
    public string Wa7dy { get; set; }
}