// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("ahkam2", Schema = "quran_quran2")]
public partial class Ahkam2
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("QuranID")]
    public int QuranId { get; set; }

    [Required]
    public string Verse { get; set; }

    [Required]
    [Column("GVerse")]
    public string Gverse { get; set; }

    public int PageNo { get; set; }

    public int PartNo { get; set; }

    public int VerseNo { get; set; }

    public int SuraNo { get; set; }

    [Required]
    [StringLength(50)]
    public string SuraName { get; set; }

    [Required]
    [Column("araby")]
    public string Araby { get; set; }

    [Required]
    [Column("gasas")]
    public string Gasas { get; set; }

    [Required]
    [Column("rwaee")]
    public string Rwaee { get; set; }

    [Required]
    [Column("gah")]
    public string Gah { get; set; }

    [Required]
    [Column("maram")]
    public string Maram { get; set; }

    [Required]
    [Column("kia")]
    public string Kia { get; set; }

    [Column("make")]
    public int Make { get; set; }
}