// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("ahkam_book", Schema = "quran_quran2")]
[Index("Feature", Name = "feature")]
public partial class AhkamBook
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("book")]
    public string Book { get; set; }

    [Required]
    [Column("Field_q")]
    public string FieldQ { get; set; }

    [Required]
    [Column("details")]
    public string Details { get; set; }

    [Column("feature")]
    public int Feature { get; set; }

    [Column("date")]
    public int Date { get; set; }

    [Column("active")]
    public short Active { get; set; }
}