// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("asbab", Schema = "quran_quran2")]
[Index("PageNo", Name = "PageNo")]
[Index("QuranId", Name = "QuranID")]
[Index("SuraNo", Name = "SuraNo")]
public partial class Asbab
{
    [Key]
    [Column("QuranID")]
    public int QuranId { get; set; }

    public int? PageNo { get; set; }

    public int? VerseNo { get; set; }

    public int? SuraNo { get; set; }

    [Required]
    [StringLength(250)]
    public string SuraName { get; set; }

    [Required]
    [Column("lebab")]
    public string Lebab { get; set; }

    [Required]
    [Column("mosnad")]
    public string Mosnad { get; set; }

    [Required]
    [Column("verse")]
    public string Verse { get; set; }

    [Required]
    [Column("3egab")]
    public string _3egab { get; set; }

    [Required]
    [Column("esti3ab")]
    public string Esti3ab { get; set; }

    [Required]
    [Column("mo7arrer")]
    public string Mo7arrer { get; set; }
}