// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("bab", Schema = "quran_quran2")]
public partial class Bab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("book_id")]
    public int BookId { get; set; }
}