// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("e3gaz", Schema = "quran_quran2")]
[Index("BabId", Name = "bab_id")]
[Index("BabId", Name = "bab_id_2")]
[Index("ChapterId", Name = "chapter_id")]
[Index("Id", Name = "id")]
[Index("SubBabId", Name = "sub_bab_id")]
public partial class E3gaz
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("matn")]
    public string Matn { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Column("sub_bab_id")]
    public int SubBabId { get; set; }

    [Column("e3gaz_book_id")]
    public int E3gazBookId { get; set; }
}