// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("e3gaz_sub_bab", Schema = "quran_quran2")]
[Index("BabId", Name = "bab_id")]
[Index("ChapterId", Name = "chapter_id")]
[Index("E3gazBookId", Name = "e3gaz_book_id")]
[Index("Id", Name = "id")]
[Index("SubBabId", Name = "sub_bab_id")]
public partial class E3gazSubBab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("e3gaz_book_id")]
    public int E3gazBookId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Column("sub_bab_id")]
    public int SubBabId { get; set; }
}