// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("e3gaz_chapters", Schema = "quran_quran2")]
[Index("ChapterId", Name = "chapter_id")]
[Index("E3gazBookId", Name = "hadith_bab_id_idx")]
public partial class E3gazChapter
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("e3gaz_book_id")]
    public int E3gazBookId { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }
}