// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("e3rab", Schema = "quran_quran2")]
public partial class E3rab
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    public int? SuraNo { get; set; }

    public string SuraName { get; set; }

    [Column("na7as")]
    public string Na7as { get; set; }

    [Column("bakoly")]
    public string Bakoly { get; set; }

    [Column("akbry")]
    public string Akbry { get; set; }

    [Column("kharat")]
    public string Kharat { get; set; }

    [Column("daas")]
    public string Daas { get; set; }

    [Column("tbian")]
    public string Tbian { get; set; }

    [Column("gadwal")]
    public string Gadwal { get; set; }

    [Column("darwish")]
    public string Darwish { get; set; }
}