// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("karat_quran", Schema = "quran_quran2")]
public partial class KaratQuran
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    [StringLength(255)]
    public string VerseNoAr { get; set; }

    public int? SuraNo { get; set; }

    [StringLength(255)]
    public string SuraName { get; set; }

    [Column("karat_vers")]
    public int? KaratVers { get; set; }

    [Column("karat_page")]
    public int? KaratPage { get; set; }

    [Column("karat_type")]
    public int? KaratType { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("status_fullImg")]
    public int? StatusFullImg { get; set; }

    [Column("code_img")]
    public string CodeImg { get; set; }

    [Column("master")]
    public int? Master { get; set; }

    [Column("mp3")]
    public int? Mp3 { get; set; }

    [Column("upd")]
    public short? Upd { get; set; }

    [Column("up_time", TypeName = "datetime")]
    public DateTime? UpTime { get; set; }
}