// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("karat_quran_org", Schema = "quran_quran2")]
public partial class KaratQuranOrg
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }

    public int? SuraNo { get; set; }

    [StringLength(250)]
    public string SuraName { get; set; }

    [Column("karat_vers")]
    public int? KaratVers { get; set; }

    [Column("karat_page")]
    public int? KaratPage { get; set; }

    [Column("karat_type")]
    public int? KaratType { get; set; }
}