// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("karat_list", Schema = "quran_quran2")]
public partial class KaratList
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }
}