// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("kerat", Schema = "quran_quran2")]
public partial class Kerat
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [Column("GVerse")]
    public string Gverse { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    [Column("ma3any")]
    public string Ma3any { get; set; }
}