// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("kerat3ashr", Schema = "quran_quran2")]
public partial class Kerat3ashr
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public int? PageNo { get; set; }

    [Column("ma3any")]
    public string Ma3any { get; set; }

    [Column("farsh")]
    public string Farsh { get; set; }
}