// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("mofradat", Schema = "quran_quran2")]
public partial class Mofradat
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("nass")]
    public string Nass { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("pageid")]
    public int? Pageid { get; set; }
}