// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("mofrad_words", Schema = "quran_quran2")]
public partial class MofradWord
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("word")]
    [StringLength(255)]
    public string Word { get; set; }

    [Column("details")]
    public string Details { get; set; }

    [Column("letter")]
    public int? Letter { get; set; }
}