// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("mogam", Schema = "quran_quran2")]
public partial class Mogam
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("chapter_id")]
    public int? ChapterId { get; set; }

    [Column("bab_id")]
    public int? BabId { get; set; }

    [Column("1text")]
    public string _1text { get; set; }

    [Column("bab_name")]
    public string BabName { get; set; }

    [Column("text")]
    public string Text { get; set; }

    [Column("book_id")]
    public int? BookId { get; set; }
}