// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("mogam_words", Schema = "quran_quran2")]
public partial class MogamWord
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("word")]
    public string Word { get; set; }

    [Column("letter")]
    public int? Letter { get; set; }

    [Column("sura")]
    public int? Sura { get; set; }

    [Column("aya")]
    public int? Aya { get; set; }

    [Column("type")]
    public string Type { get; set; }

    [Column("pageno")]
    public int? Pageno { get; set; }
}