// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("mogam_book", Schema = "quran_quran2")]
public partial class MogamBook
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("about")]
    public string About { get; set; }

    [Column("date")]
    public int? Date { get; set; }
}