// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("multimedia_categories", Schema = "quran_quran2")]
public partial class MultimediaCategory
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("name")]
    [StringLength(300)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(500)]
    public string Description { get; set; }

    [Column("view")]
    public int? View { get; set; }

    [Column("photo")]
    [StringLength(400)]
    public string Photo { get; set; }

    [Column("type")]
    public int? Type { get; set; }

    [Column("sort")]
    public int? Sort { get; set; }

    [Column("user_add")]
    public int? UserAdd { get; set; }

    [Column("create_date")]
    [Precision(0)]
    public DateTime? CreateDate { get; set; }

    [Column("status")]
    public short? Status { get; set; }

    [Column("lang")]
    public int? Lang { get; set; }

    [Column("section_type")]
    public int? SectionType { get; set; }
}