// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("multimedia_lecturer", Schema = "quran_quran2")]
public partial class MultimediaLecturer
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("name")]
    [StringLength(1000)]
    public string Name { get; set; }

    [Column("creat_date")]
    [Precision(0)]
    public DateTime? CreatDate { get; set; }

    [Column("status")]
    public short? Status { get; set; }

    [Column("photo")]
    [StringLength(800)]
    public string Photo { get; set; }

    [Column("descripton")]
    public string Descripton { get; set; }

    [Column("user_add")]
    public int? UserAdd { get; set; }

    [Column("create_date", TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }
}