// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("multimedia", Schema = "quran_quran2")]
public partial class Multimedium
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("src")]
    public string Src { get; set; }

    [Column("photo")]
    [StringLength(500)]
    public string Photo { get; set; }

    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("lecturer")]
    public int? Lecturer { get; set; }

    [Column("sura")]
    public int? Sura { get; set; }

    [Column("type")]
    public int? Type { get; set; }

    [Column("publish_status")]
    [Precision(0)]
    public DateTime? PublishStatus { get; set; }

    [Column("description")]
    [StringLength(1000)]
    public string Description { get; set; }

    [Column("categories")]
    public int? Categories { get; set; }

    [Column("view")]
    public int? View { get; set; }

    [Column("status")]
    public short? Status { get; set; }

    [Column("homepage")]
    public short? Homepage { get; set; }

    [Column("facebook_like")]
    public int? FacebookLike { get; set; }

    [Column("facebook_comment")]
    public int? FacebookComment { get; set; }

    [Column("facebook_share")]
    public int? FacebookShare { get; set; }

    [Column("facebook_commentbox")]
    public int? FacebookCommentbox { get; set; }

    [Column("facebook_total_count")]
    public int? FacebookTotalCount { get; set; }

    [Column("linkedin_count")]
    public int? LinkedinCount { get; set; }

    [Column("total_socialmedia")]
    public int? TotalSocialmedia { get; set; }

    [Column("twitter_count")]
    public int? TwitterCount { get; set; }

    [Column("lang")]
    public int? Lang { get; set; }

    [Column("user_add")]
    public int? UserAdd { get; set; }

    [Column("create_date")]
    [Precision(0)]
    public DateTime? CreateDate { get; set; }
}