// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("olom_bab", Schema = "quran_quran2")]
public partial class OlomBab
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("chapter_id")]
    public int? ChapterId { get; set; }

    [Column("olom_book_id")]
    public int? OlomBookId { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("bab_id")]
    public int? BabId { get; set; }
}