// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("olom_book", Schema = "quran_quran2")]
public partial class OlomBook
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("book")]
    public string Book { get; set; }

    [Column("Field_q")]
    public string FieldQ { get; set; }

    [Column("details")]
    public string Details { get; set; }

    [Column("feature")]
    public int? Feature { get; set; }

    [Column("date")]
    public int? Date { get; set; }

    [Column("active")]
    public short? Active { get; set; }
}