// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

public partial class Quran_quran3Context : DbContext
{
    public Quran_quran3Context()
    {
    }

    public Quran_quran3Context(DbContextOptions<Quran_quran3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<A7kam> A7kams { get; set; }

    public virtual DbSet<Admin> Admins { get; set; }

    public virtual DbSet<Ahkam> Ahkams { get; set; }

    public virtual DbSet<Ahkam2> Ahkam2s { get; set; }

    public virtual DbSet<AhkamBook> AhkamBooks { get; set; }

    public virtual DbSet<Asbab> Asbabs { get; set; }

    public virtual DbSet<AsbabBook> AsbabBooks { get; set; }

    public virtual DbSet<Bab> Babs { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<E3gaz> E3gazs { get; set; }

    public virtual DbSet<E3gazBab> E3gazBabs { get; set; }

    public virtual DbSet<E3gazBook> E3gazBooks { get; set; }

    public virtual DbSet<E3gazChapter> E3gazChapters { get; set; }

    public virtual DbSet<E3gazSubBab> E3gazSubBabs { get; set; }

    public virtual DbSet<E3rab> E3rabs { get; set; }

    public virtual DbSet<E3rabBook> E3rabBooks { get; set; }

    public virtual DbSet<KaratList> KaratLists { get; set; }

    public virtual DbSet<KaratQuran> KaratQurans { get; set; }

    public virtual DbSet<KaratQuranOrg> KaratQuranOrgs { get; set; }

    public virtual DbSet<Kerat> Kerats { get; set; }

    public virtual DbSet<Kerat3ashr> Kerat3ashrs { get; set; }

    public virtual DbSet<Ma3any> Ma3anies { get; set; }

    public virtual DbSet<Ma3anyBook> Ma3anyBooks { get; set; }

    public virtual DbSet<MofradLetter> MofradLetters { get; set; }

    public virtual DbSet<MofradWord> MofradWords { get; set; }

    public virtual DbSet<Mofradat> Mofradats { get; set; }

    public virtual DbSet<Mogam> Mogams { get; set; }

    public virtual DbSet<MogamBook> MogamBooks { get; set; }

    public virtual DbSet<MogamWord> MogamWords { get; set; }

    public virtual DbSet<Moshabeh> Moshabehs { get; set; }

    public virtual DbSet<Moshabeh1> Moshabeh1s { get; set; }

    public virtual DbSet<MultimediaCategory> MultimediaCategories { get; set; }

    public virtual DbSet<MultimediaLecturer> MultimediaLecturers { get; set; }

    public virtual DbSet<Multimedium> Multimedia { get; set; }

    public virtual DbSet<Olom> Oloms { get; set; }

    public virtual DbSet<OlomBab> OlomBabs { get; set; }

    public virtual DbSet<OlomBook> OlomBooks { get; set; }

    public virtual DbSet<OlomChapter> OlomChapters { get; set; }

    public virtual DbSet<OlomSubBab> OlomSubBabs { get; set; }

    public virtual DbSet<Quran> Qurans { get; set; }

    public virtual DbSet<Quran3> Quran3s { get; set; }

    public virtual DbSet<QuranSound> QuranSounds { get; set; }

    public virtual DbSet<Reciter> Reciters { get; set; }

    public virtual DbSet<Sura> Suras { get; set; }

    public virtual DbSet<SuraSound> SuraSounds { get; set; }

    public virtual DbSet<Sverse> Sverses { get; set; }

    public virtual DbSet<TLang> TLangs { get; set; }

    public virtual DbSet<Tafseeer> Tafseeers { get; set; }

    public virtual DbSet<Tafseer> Tafseers { get; set; }

    public virtual DbSet<TafseerBook> TafseerBooks { get; set; }

    public virtual DbSet<TafseerEnglish> TafseerEnglishes { get; set; }

    public virtual DbSet<TafseerNaboy> TafseerNaboys { get; set; }

    public virtual DbSet<TafseerPage> TafseerPages { get; set; }

    public virtual DbSet<Tagwed> Tagweds { get; set; }

    public virtual DbSet<TagwedBook> TagwedBooks { get; set; }

    public virtual DbSet<Tragem> Tragems { get; set; }

    public virtual DbSet<TragemBook> TragemBooks { get; set; }

    public virtual DbSet<Warsh> Warshes { get; set; }

    public virtual DbSet<Word> Words { get; set; }

    public virtual DbSet<_3egab> _3egabs { get; set; }

    public virtual DbSet<_3othaymen2> _3othaymen2s { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=URANUS\\DEV;Database=Quran_quran3;User Id=ils;Password=ils@123;MultipleActiveResultSets=true;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<A7kam>(entity =>
        {
            entity.Property(e => e.English).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Germany).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ibnkathir).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kadeer).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kashaf).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kortoby).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Meaning1).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Meaning2).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Sa3dy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Safwa).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.SuraName).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Tabary).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Wa7dy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Zelal).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_admins_id");
        });

        modelBuilder.Entity<Ahkam>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ahkam_id");
        });

        modelBuilder.Entity<Ahkam2>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ahkam2_id");
        });

        modelBuilder.Entity<AhkamBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ahkam_book_id");

            entity.Property(e => e.Active).HasDefaultValue((short)1);
        });

        modelBuilder.Entity<Asbab>(entity =>
        {
            entity.HasKey(e => e.QuranId).HasName("PK_asbab_QuranID");

            entity.Property(e => e.PageNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.VerseNo).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<AsbabBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_asbab_book_id");

            entity.Property(e => e.Active).HasDefaultValue((short)1);
        });

        modelBuilder.Entity<Bab>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_bab_id");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_chapter_id");
        });

        modelBuilder.Entity<E3gaz>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3gaz_id");
        });

        modelBuilder.Entity<E3gazBab>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3gaz_bab_id");
        });

        modelBuilder.Entity<E3gazBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3gaz_book_id");

            entity.Property(e => e.Active).HasDefaultValue((short)1);
        });

        modelBuilder.Entity<E3gazChapter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3gaz_chapters_id");
        });

        modelBuilder.Entity<E3gazSubBab>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3gaz_sub_bab_id");
        });

        modelBuilder.Entity<E3rabBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_e3rab_book_id");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FieldQ).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Kerat>(entity =>
        {
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ma3any).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.SuraName).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<MofradLetter>(entity =>
        {
            entity.Property(e => e.Letter).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<MofradWord>(entity =>
        {
            entity.Property(e => e.Details).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Word).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Quran3>(entity =>
        {
            entity.Property(e => e.Adwa).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Alosy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Aysar).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ba3awy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Baedawy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Bnothemen).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.English).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ezzsalam).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Germany).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Hatem).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ibnkathir).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kadeer).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kashaf).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Kortoby).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Mafateh).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Mara7).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Mawrdy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Meaning1).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Meaning2).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Mo7et).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Mokatel).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Montkab).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Nasafy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Qatan).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Sa3dy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Safwa).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Sha3rawy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.ShortIbnkathir).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.SuraName).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Sverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Ta7reer).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Tabary).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Wa7dy).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Waseet).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Zelal).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Reciter>(entity =>
        {
            entity.HasKey(e => e.ReciterId).HasName("PK_reciters_ReciterID");
        });

        modelBuilder.Entity<Sura>(entity =>
        {
            entity.HasKey(e => e.SuraNo).HasName("PK_sura_SuraNo");

            entity.Property(e => e.SuraName).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Verses).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<SuraSound>(entity =>
        {
            entity.HasKey(e => e.SuraNo).HasName("PK_sura_sound_SuraNo");

            entity.Property(e => e.SuraName).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Verses).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Sverse>(entity =>
        {
            entity.HasKey(e => e.SverseNo).HasName("PK_sverse_sverseNo");

            entity.Property(e => e.SverseName).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Title).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Type).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<TLang>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_t_lang_id");

            entity.Property(e => e.Lang).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Name).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Sura).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Tafseeer>(entity =>
        {
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.SuraName).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Tafseer>(entity =>
        {
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<TafseerBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tafseer_book_id");

            entity.Property(e => e.Active).HasDefaultValue((short)1);
        });

        modelBuilder.Entity<TafseerEnglish>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tafseer_english_id");

            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.PageNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PartNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.QuranId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraName).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.VerseNo).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<TafseerPage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tafseer_pages_id");

            entity.Property(e => e.UpdateTime).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Tagwed>(entity =>
        {
            entity.Property(e => e.SuraName).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<TagwedBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tagwed_book_id");

            entity.Property(e => e.Book).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.FieldQ).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Tragem>(entity =>
        {
            entity.Property(e => e.EngAhmedAli).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngAhmedRazaKhan).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngArberry).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngAsad).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngClearQuranAllah).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngClearQuranGod).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngCommunityAllah).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngCommunityGod).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngDaryabadi).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngHilaliAndKhan).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngKhattab).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngMaududi).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngMubarakpuri).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngPickthall).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngQarai).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngQaribullahAndDarwish).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngSarwar).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.EngYusufAli).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.English2).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Fh).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Germany).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Gverse).UseCollation("Arabic_CI_AS");
            entity.Property(e => e.Verse).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<TragemBook>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tragem_book_id");

            entity.Property(e => e.Active).HasDefaultValue(1);
            entity.Property(e => e.FieldQ).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<Warsh>(entity =>
        {
            entity.Property(e => e.PageId).UseCollation("Arabic_CI_AS");
        });

        modelBuilder.Entity<_3egab>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_3egab_id");
        });

        modelBuilder.Entity<_3othaymen2>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_3othaymen2_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}