// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("quran3", Schema = "quran_quran2")]
public partial class Quran3
{
    [Column("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [Column("GVerse")]
    public string Gverse { get; set; }

    [Column("sverse")]
    public string Sverse { get; set; }

    public string Meaning1 { get; set; }

    public string Meaning2 { get; set; }

    public string English { get; set; }

    public string Germany { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    [Column("tabary")]
    public string Tabary { get; set; }

    [Column("kortoby")]
    public string Kortoby { get; set; }

    [Column("safwa")]
    public string Safwa { get; set; }

    [Column("ibnkathir")]
    public string Ibnkathir { get; set; }

    [Column("kashaf")]
    public string Kashaf { get; set; }

    [Column("zelal")]
    public string Zelal { get; set; }

    [Column("sa3dy")]
    public string Sa3dy { get; set; }

    [Column("kadeer")]
    public string Kadeer { get; set; }

    [Column("wa7dy")]
    public string Wa7dy { get; set; }

    [Column("short_ibnkathir")]
    public string ShortIbnkathir { get; set; }

    [Column("sha3rawy")]
    public string Sha3rawy { get; set; }

    [Column("mo7et")]
    public string Mo7et { get; set; }

    [Column("aysar")]
    public string Aysar { get; set; }

    [Column("ba3awy")]
    public string Ba3awy { get; set; }

    [Column("nasafy")]
    public string Nasafy { get; set; }

    [Column("mawrdy")]
    public string Mawrdy { get; set; }

    [Column("montkab")]
    public string Montkab { get; set; }

    [Column("hatem")]
    public string Hatem { get; set; }

    [Column("bnothemen")]
    public string Bnothemen { get; set; }

    [Column("mafateh")]
    public string Mafateh { get; set; }

    [Column("mara7")]
    public string Mara7 { get; set; }

    [Column("mokatel")]
    public string Mokatel { get; set; }

    [Column("adwa")]
    public string Adwa { get; set; }

    [Column("baedawy")]
    public string Baedawy { get; set; }

    [Column("waseet")]
    public string Waseet { get; set; }

    [Column("alosy")]
    public string Alosy { get; set; }

    [Column("ezzsalam")]
    public string Ezzsalam { get; set; }

    [Column("qatan")]
    public string Qatan { get; set; }

    [Column("ta7reer")]
    public string Ta7reer { get; set; }
}