// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("quran", Schema = "quran_quran2")]
public partial class Quran
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("QuranID")]
    public int? QuranId { get; set; }

    [Column("verse")]
    public string Verse { get; set; }

    [Column("verseNoSign")]
    public string VerseNoSign { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    [Column("hezbNo")]
    public int? HezbNo { get; set; }

    [Column("rob3No")]
    public int? Rob3No { get; set; }

    public int? VerseNo { get; set; }

    public string VerseNoAr { get; set; }

    public int? SuraNo { get; set; }

    [StringLength(250)]
    public string SuraName { get; set; }

    [Column("sound")]
    [StringLength(10)]
    public string Sound { get; set; }

    [Column("img_warsh")]
    [StringLength(255)]
    public string ImgWarsh { get; set; }

    [Column("search_ayaa")]
    public string SearchAyaa { get; set; }

    [Column("verse3_old")]
    public string Verse3Old { get; set; }

    [Column("2verse")]
    public string _2verse { get; set; }
}