// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("reciters", Schema = "quran_quran2")]
public partial class Reciter
{
    [Key]
    [Column("ReciterID")]
    public int ReciterId { get; set; }

    [Required]
    [Column("ar_name")]
    public string ArName { get; set; }

    [Required]
    [Column("en_name")]
    public string EnName { get; set; }

    [Required]
    [Column("folder")]
    public string Folder { get; set; }

    [Column("karat")]
    public int Karat { get; set; }
}