// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("sura_sound", Schema = "quran_quran2")]
public partial class SuraSound
{
    [Key]
    public long SuraNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? Verses { get; set; }

    [Required]
    [StringLength(255)]
    public string Type { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("no_of_words")]
    public int NoOfWords { get; set; }

    [Column("no_of_letters")]
    public int NoOfLetters { get; set; }

    [Column("no_of_ghonna")]
    public int NoOfGhonna { get; set; }

    [Column("no_of_glala")]
    public int NoOfGlala { get; set; }
}