// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("sura", Schema = "quran_quran2")]
public partial class Sura
{
    [Key]
    public long SuraNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? Verses { get; set; }

    [Required]
    [StringLength(255)]
    public string Type { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("karat_type")]
    public int KaratType { get; set; }

    [Column("master")]
    public int Master { get; set; }

    [Required]
    [Column("sabb_tasmia")]
    public string SabbTasmia { get; set; }

    [Required]
    [Column("ta3reef")]
    public string Ta3reef { get; set; }

    [Required]
    [Column("mwadee3")]
    public string Mwadee3 { get; set; }

    [Required]
    [Column("sabb_nzol")]
    public string SabbNzol { get; set; }

    [Required]
    [Column("fadl")]
    public string Fadl { get; set; }
}