// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("sverse", Schema = "quran_quran2")]
public partial class Sverse
{
    [Key]
    [Column("sverseNo")]
    public long SverseNo { get; set; }

    [Column("sverseName")]
    [StringLength(50)]
    public string SverseName { get; set; }

    public int? Verses { get; set; }

    [StringLength(255)]
    public string Type { get; set; }

    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }
}