// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("tafseer_naboy", Schema = "quran_quran2")]
public partial class TafseerNaboy
{
    [Column("id")]
    public int? Id { get; set; }

    public int? VerseNo { get; set; }

    [Column("selid")]
    public int? Selid { get; set; }

    public int? SuraNo { get; set; }

    [Column("taraf")]
    public string Taraf { get; set; }

    [Column("book_name")]
    [StringLength(100)]
    public string BookName { get; set; }

    [Column("hadith_txt")]
    public string HadithTxt { get; set; }

    [Column("hadith_search")]
    public string HadithSearch { get; set; }

    [Column("status")]
    public int? Status { get; set; }
}