// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("tafseer", Schema = "quran_quran2")]
public partial class Tafseer
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [Column("GVerse")]
    public string Gverse { get; set; }

    [Column("elgalalen")]
    public string Elgalalen { get; set; }

    [Column("ibnkathir")]
    public string Ibnkathir { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    [StringLength(50)]
    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    [Column("tabary1")]
    public string Tabary1 { get; set; }

    [Column("mo7et")]
    public string Mo7et { get; set; }

    [Column("kortoby")]
    public string Kortoby { get; set; }

    [Column("safwa")]
    public string Safwa { get; set; }

    [Column("kashaf")]
    public string Kashaf { get; set; }

    [Column("zelal")]
    public string Zelal { get; set; }

    [Column("sa3dy")]
    public string Sa3dy { get; set; }

    [Column("kadeer")]
    public string Kadeer { get; set; }

    [Column("elmoysar")]
    public string Elmoysar { get; set; }

    [Column("wa7dy")]
    public string Wa7dy { get; set; }

    [Column("qatan")]
    public string Qatan { get; set; }

    [Column("ezzsalam")]
    public string Ezzsalam { get; set; }

    [Column("elwaseet")]
    public string Elwaseet { get; set; }

    [Column("baedawy")]
    public string Baedawy { get; set; }

    [Column("short_ibnkathir")]
    public string ShortIbnkathir { get; set; }

    [Column("aysar")]
    public string Aysar { get; set; }

    [Column("ba3awy")]
    public string Ba3awy { get; set; }

    [Column("nasafy")]
    public string Nasafy { get; set; }

    [Column("montkab")]
    public string Montkab { get; set; }

    [Column("mawrdy")]
    public string Mawrdy { get; set; }

    [Column("hatem")]
    public string Hatem { get; set; }

    [Column("bnothemen")]
    public string Bnothemen { get; set; }

    [Column("mafateh")]
    public string Mafateh { get; set; }

    [Column("mara7")]
    public string Mara7 { get; set; }

    [Column("mokatel")]
    public string Mokatel { get; set; }

    [Column("adwa")]
    public string Adwa { get; set; }

    [Column("ta7reer")]
    public string Ta7reer { get; set; }

    [Column("safwat")]
    public string Safwat { get; set; }

    [Column("arafa")]
    public string Arafa { get; set; }

    [Column("many")]
    public string Many { get; set; }

    [Column("sha3rawy")]
    public string Sha3rawy { get; set; }

    [Column("manar2")]
    public string Manar2 { get; set; }

    [Column("manar")]
    public string Manar { get; set; }

    [Column("maser")]
    public string Maser { get; set; }

    [Column("dor")]
    public string Dor { get; set; }

    [Column("zahra")]
    public string Zahra { get; set; }

    [Column("saood")]
    public string Saood { get; set; }

    [Column("moqatel")]
    public string Moqatel { get; set; }

    [Column("dorar")]
    public string Dorar { get; set; }

    [Column("qasmi")]
    public string Qasmi { get; set; }

    [Column("mafateh1")]
    public string Mafateh1 { get; set; }

    [Column("sa3dy1")]
    public string Sa3dy1 { get; set; }

    [Column("zelal1")]
    public string Zelal1 { get; set; }

    [Column("wageez")]
    public string Wageez { get; set; }

    [Column("mason")]
    public string Mason { get; set; }

    [Column("kashaf1")]
    public string Kashaf1 { get; set; }

    [Column("bian")]
    public string Bian { get; set; }

    [Column("mojahed")]
    public string Mojahed { get; set; }

    [Column("sofian")]
    public string Sofian { get; set; }

    [Column("ibnkathirturkey")]
    public string Ibnkathirturkey { get; set; }

    [Column("tabaryturkey")]
    public string Tabaryturkey { get; set; }

    [Column("saood2")]
    public string Saood2 { get; set; }

    [Column("ta7reer2")]
    public string Ta7reer2 { get; set; }

    [Column("tasheel")]
    public string Tasheel { get; set; }

    [Column("razzaq")]
    public string Razzaq { get; set; }

    [Column("baseet")]
    public string Baseet { get; set; }

    [Column("eegy")]
    public string Eegy { get; set; }

    [Column("mara3i")]
    public string Mara3i { get; set; }

    [Column("3azb")]
    public string _3azb { get; set; }

    [Column("hatem1")]
    public string Hatem1 { get; set; }

    [Column("safwat1")]
    public string Safwat1 { get; set; }

    [Column("adwa1")]
    public string Adwa1 { get; set; }

    [Column("kashaf2")]
    public string Kashaf2 { get; set; }

    [Column("tabary_old")]
    public string TabaryOld { get; set; }

    [Column("wa7dy1")]
    public string Wa7dy1 { get; set; }

    [Column("sha3rawy_new")]
    public string Sha3rawyNew { get; set; }

    [Column("ibnkathir_new")]
    public string IbnkathirNew { get; set; }

    [Column("up_data")]
    public int? UpData { get; set; }

    [Column("dor1")]
    public string Dor1 { get; set; }

    [Column("saood1")]
    public string Saood1 { get; set; }

    [Column("many1")]
    public string Many1 { get; set; }

    [Column("many2")]
    public string Many2 { get; set; }

    [Column("qasmi1")]
    public string Qasmi1 { get; set; }

    [Column("manar1")]
    public string Manar1 { get; set; }

    [Column("ta7reer1")]
    public string Ta7reer1 { get; set; }

    [Column("qatan1")]
    public string Qatan1 { get; set; }

    [Column("books_full")]
    public int? BooksFull { get; set; }
}