// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("tafseer_pages", Schema = "quran_quran2")]
public partial class TafseerPage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("tafseer_book")]
    [StringLength(200)]
    public string TafseerBook { get; set; }

    [Column("page_no")]
    public int PageNo { get; set; }

    [Column("verse_no")]
    public int VerseNo { get; set; }

    [Column("verse_count")]
    public int VerseCount { get; set; }

    [Column("sura_no")]
    public int SuraNo { get; set; }

    [Required]
    [Column("sura_name")]
    [StringLength(500)]
    public string SuraName { get; set; }

    [Column("repater")]
    public short Repater { get; set; }

    [Column("m_pageno")]
    public int MPageno { get; set; }

    [Column("m_quranid")]
    public int MQuranid { get; set; }

    [Column("cheak_repater")]
    public int CheakRepater { get; set; }

    [Column("updateTime", TypeName = "datetime")]
    public DateTime UpdateTime { get; set; }
}