// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("t_lang", Schema = "quran_quran2")]
[Index("Id", Name = "id")]
public partial class TLang
{
    [Column("lang")]
    public string Lang { get; set; }

    [Column("sura")]
    public string Sura { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }
}