// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("tragem", Schema = "quran_quran2")]
public partial class Tragem
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("QuranID")]
    public int? QuranId { get; set; }

    public string Verse { get; set; }

    [Column("GVerse")]
    public string Gverse { get; set; }

    public string English { get; set; }

    [Column("english2")]
    public string English2 { get; set; }

    [Column("Eng_Ahmed_Ali")]
    public string EngAhmedAli { get; set; }

    [Column("Eng_Yusuf_Ali")]
    public string EngYusufAli { get; set; }

    [Column("Eng_Qarai")]
    public string EngQarai { get; set; }

    [Column("Eng_Ahmed_Raza_Khan")]
    public string EngAhmedRazaKhan { get; set; }

    [Column("Eng_Arberry")]
    public string EngArberry { get; set; }

    [Column("Eng_Asad")]
    public string EngAsad { get; set; }

    [Column("Eng_Daryabadi")]
    public string EngDaryabadi { get; set; }

    [Column("Eng_Hilali_And_Khan")]
    public string EngHilaliAndKhan { get; set; }

    [Column("Eng_ClearQuran_God")]
    public string EngClearQuranGod { get; set; }

    [Column("Eng_ClearQuran_Allah")]
    public string EngClearQuranAllah { get; set; }

    [Column("Eng_Community_God")]
    public string EngCommunityGod { get; set; }

    [Column("Eng_Community_Allah")]
    public string EngCommunityAllah { get; set; }

    [Column("Eng_Khattab")]
    public string EngKhattab { get; set; }

    [Column("Eng_Maududi")]
    public string EngMaududi { get; set; }

    [Column("Eng_Mubarakpuri")]
    public string EngMubarakpuri { get; set; }

    [Column("Eng_Pickthall")]
    public string EngPickthall { get; set; }

    [Column("Eng_Sarwar")]
    public string EngSarwar { get; set; }

    [Column("Eng_Qaribullah_And_Darwish")]
    public string EngQaribullahAndDarwish { get; set; }

    public string Germany { get; set; }

    public int? PageNo { get; set; }

    public int? PartNo { get; set; }

    public int? VerseNo { get; set; }

    public string SuraName { get; set; }

    public int? SuraNo { get; set; }

    [Column("japanese")]
    public string Japanese { get; set; }

    [Column("chinese")]
    public string Chinese { get; set; }

    [Column("italy")]
    public string Italy { get; set; }

    [Column("fr")]
    public string Fr { get; set; }

    [Column("fr2")]
    public string Fr2 { get; set; }

    [Column("indo")]
    public string Indo { get; set; }

    [Column("kory")]
    public string Kory { get; set; }

    [Column("sa7ly")]
    public string Sa7ly { get; set; }

    [Column("rusha")]
    public string Rusha { get; set; }

    [Column("alb")]
    public string Alb { get; set; }

    [Column("sp")]
    public string Sp { get; set; }

    [Column("hendi")]
    public string Hendi { get; set; }

    [Column("malawy")]
    public string Malawy { get; set; }

    [Column("polg")]
    public string Polg { get; set; }

    [Column("polsh")]
    public string Polsh { get; set; }

    [Column("posna")]
    public string Posna { get; set; }

    [Column("ty")]
    public string Ty { get; set; }

    [Column("fares")]
    public string Fares { get; set; }

    [Column("torki")]
    public string Torki { get; set; }

    [Column("azer")]
    public string Azer { get; set; }

    [Column("braz")]
    public string Braz { get; set; }

    [Column("sere")]
    public string Sere { get; set; }

    [Column("fin")]
    public string Fin { get; set; }

    [Column("english_shaker")]
    public string EnglishShaker { get; set; }

    [Column("german2")]
    public string German2 { get; set; }

    [Column("fh")]
    public string Fh { get; set; }
}