// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Table("tragem_book", Schema = "quran_quran2")]
public partial class TragemBook
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("book")]
    public string Book { get; set; }

    [Column("Field_q")]
    public string FieldQ { get; set; }

    [Column("active")]
    public int Active { get; set; }

    [Column("status")]
    public short Status { get; set; }
}