// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("warsh", Schema = "quran_quran2")]
public partial class Warsh
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("page_id")]
    [StringLength(100)]
    public string PageId { get; set; }

    [Column("image")]
    [StringLength(100)]
    public string Image { get; set; }
}