// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.Models;

[Keyless]
[Table("words", Schema = "quran_quran2")]
public partial class Word
{
    [Column("wordid")]
    public int? Wordid { get; set; }

    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("sura_id")]
    public int? SuraId { get; set; }

    [Column("QuranID")]
    public int? QuranId { get; set; }

    [Column("score")]
    public int? Score { get; set; }

    [Column("pageno")]
    public int? Pageno { get; set; }
}