// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("Ahkam")]
//[Keyless]
public  class Ahkam // reviewed
{

    //[OldName("id")]
    public int Id { get; set; }

    [OldName("QuranID")]
    public int? AyaId { get; set; }
    public Aya Aya { get; set; }


    [OldName("araby")]
    [Required]
    public string Araby { get; set; }//TODO: Referes to what  => ابن العربي 

    [OldName("gasas")]
    [Required]
    public string Gasas { get; set; }//TODO: Referes to what  => الجصاص

    [OldName("rwaee")]
    [Required]
    public string Rwaee { get; set; } //TODO: Referes to what => روائع البيان

    [OldName("gah")]
    [Required]
    public string Gahdamy { get; set; } //TODO: Referes to what  => الجهضمي

    [OldName("maram")]
    [Required]
    public string NaylMaram { get; set; }//TODO: Referes to what  => نيل المرام

    [OldName("kia")]
    [Required]
    public string Kiaharsy { get; set; } //TODO: Referes to what  => كيا هرسي

}