// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("asbab_book")]
//[Keyless]
public  class AsbabNozoolBook //reviewed for Asbab Al-Nozool  أسباب النزول
{
    //[OldName("id")]
    
    public int Id { get; set; }

    [OldName("book")]
    [Required]
    public string Book { get; set; }
}