// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("asbab")]
//[Keyless]
public  class AsbabNozool // this is for Asbab Al-Nozool  أسباب النزول reviewed
{
    public int Id { get; set; }

    [OldName("QuranID")]
    public int AyaId { get; set; } 
    public Aya Aya { get; set; }

    [OldName("lebab")]
    [Required]
    public string Lebab { get; set; } //TODO: Referes to what  => لباب النقول

    [OldName("mosnad")]
    [Required]
    public string Mosnad { get; set; }//TODO: Referes to what  => صحيح المسند من اسباب النزول
    
    [OldName("3egab")]
    [Required]
    public string Eegab { get; set; } // TODO: Referes to what  => العجاب في بيان الاسباب

    [OldName("esti3ab")]
    [Required]
    public string Esteaab { get; set; } //TODO: Referes to what  => الاستيعاب في بيان الاسباب

    [OldName("mo7arrer")]
    [Required]
    public string Moharrer { get; set; } //TODO: Referes to what  => المحرر في اسباب النزول
}