// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Keyless]
[OldName("Quran")]
public  class Aya
{

    //public int FakeId { get; set; }
    [OldName("QuranID")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Key]
    public int? Id { get; set; }
 
    [OldName("verse")]
    public string Verse { get; set; }

    [OldName("verseNoSign")]
    public string VerseNoSign { get; set; }
    [OldName("PageNo")]
    public int? PageNo { get; set; }
    [OldName("PartNo")]
    public int? PartNo { get; set; }

    [OldName("hezbNo")]
    public int? HezbNo { get; set; }

    [OldName("rob3No")]
    public int? RobeeNo { get; set; }
    [OldName("VerseNo")]
    public int? VerseNo { get; set; }
    [OldName("VerseNoAr")]
    public string VerseNoAr { get; set; }
    [OldName("SuraNo")]
    public int? SuraId { get; set; } // Navigation property to Sura
    public Sura Sura { get; set; }

    [OldName("sound")]
    public string Sound { get; set; }

    [OldName("img_warsh")]
    public string ImgWarsh { get; set; }




    public int? BeginningLetterId { get; set; }
}




