// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("e3gaz_chapters")]
//[Keyless]
public  class EgazChapter//reviewed
{
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }
    
    [OldName("e3gaz_book_id")]
    public int EgazBookId { get; set; }
    [ForeignKey(nameof(EgazBookId))]
    public EgazBook EgazBook { get; set; }
    

    [OldName("chapter_id")]
    public int EgazChapterNo { get; set; }


    //public ICollection<EgazBab> EgazBabs { get; set; }
    //public ICollection<EgazSubBab> EgazSubBabs { get; set; }
    //public ICollection<Egaz> EgazItems { get; set; } //TODO:rename to EgazItems
}