// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


[OldName("e3gaz")]
//[Keyless]
public  class Egaz // reviewed
{
    //[OldName("id")]

    public int Id { get; set; }

    [OldName("matn")]
    [Required]
    public string Matn { get; set; }

    [OldName("new_bab_id")]
    public int BabId { get; set; } // foreign key to OlomBab
    public EgazBab Bab { get; set; }


}