// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;
using MosshafContextHandeling.Models;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("e3gaz_bab")]
//[Keyless]
public  class EgazBab //reviewed
{
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [OldName("name")]
    [Required]
    public string Name { get; set; }

    [OldName("new_chapter_id")]
    public int? ChapterId { get; set; }
    public EgazChapter Chapter { get; set; }


    [OldName("parent_id")]
    public int? ParentId { get; set; }
    public EgazBab Parent { get; set; }


    [OldName("chapter_id")]
    public int EgazChapterNo { get; set; }

    [OldName("e3gaz_book_id")]
    public int EgazBookNo { get; set; }
    [OldName("bab_id")]
    public int BabNo { get; set; }

}