// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("e3rab")]

public  class Erab //reviewed
{
    public int Id { get; set; }

    [OldName("QuranID")]
    public int AyaId { get; set; }
    public Aya Aya { get; set; }

    [OldName("na7as")]
    public string Nahas { get; set; }//النحاس في الاعراب


    [OldName("kharat")]
    public string Kharat { get; set; }//الخراط

    [OldName("daas")]
    public string Daas { get; set; } //دعاس 

    [OldName("tbian")]
    public string Tbian { get; set; }//التبيان في الاعراب

    [OldName("gadwal")]
    public string Gadwal { get; set; } //الجدول في الاعراب

    [OldName("darwish")]
    public string Darwish { get; set; } // الدروايش في الاعراب
}