// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("ma3any_book")]
public  class MaanyBook//reviewed
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    public string Name { get; set; }
    public ICollection<MaanyBook> MaanyBooks { get; set; }
    //ناقص كتاب مخلوف ف الداتا
}