// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("ma3any")]
public class Maany//reviewed
{

    [Key]
    public int Id { get; set; }

    [OldName("PageNo")]
    public int? PageNo { get; set; }

    [OldName("ma3any")]
    public string Text { get; set; }

    [OldName("book_id")]
    public int? MaanyBookId { get; set; }
    public MaanyBook MaanyBook { get; set; } // Navigation property
}