// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mogam")]
public  class Mogam // reviewed for Mogam  معجم
{
    //[OldName("id")]
    public int Id { get; set; }

    [OldName("text")]
    public string Nass { get; set; }


    [OldName("new_bab_id")]
    public int MogamBabId { get; set; }
    public MogamBab MogamBab { get; set; }

    //Navigation Properties
    [OldName("chapter_id")]
    public int? MogamChapterNo { get; set; }

    [OldName("bab_id")]
    public int? MogamBabNo { get; set; }

    [OldName("book_id")]
    public int? MogamBookNo { get; set; }

    //public  MogamBook? MogamBook { get; set; } // Navigation property
    //public MogamChapter? MogamChapter { get; set; } // Navigation property
    //public MogamBab? MogamBab { get; set; } // Navigation property
}