// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("chapter")]
public  class MogamChapter 
{
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [OldName("name")]
    public string Name { get; set; }

    [OldName("chapter_id")]
    public int ChapterNo { get; set; } //TODO: if it isn't a forignkey change to ChapterNumber  دول متخزن فيهم ارقامهم على حسب حروف اللغه العربيه 

    [OldName("book_id")]
    public int MogamBookId { get; set; } 
    public MogamBook MogamBook { get; set; }

    public ICollection<MogamBab> MogamBabs { get; set; }

}