// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("mogam_book")]
public  class MogamBook //reviewed for Mogam  معجم
{
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int? Id { get; set; }

    [OldName("name")]
    public string Name { get; set; }


    public ICollection<MogamChapter> MogamChapters { get; set; }
    ////public ICollection<MogamBab> MogamBabs { get; set; }
}