// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("bab")]
public  class MogamBab//reviewed for Mogam  معجم
{
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [OldName("name")]
    public string Name { get; set; }
    
    [OldName("new_chapter_id")]
    public int MogamChapterId { get; set; }
    public MogamChapter Chapter { get; set; }

    [OldName("chapter_id")]
    public int MogamChapterNo { get; set; }

    public ICollection<Mogam> Mogams { get; set; }

}