// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("moshabeh")]
public  class Moshabeh 
{// reviewed 
    public int Id { get; set; } 

    [OldName("PageNo")]
    public int? PageNo { get; set; } 

    [OldName("ma3any")]
    public string Nass { get; set; }
    
}