// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia")]

public  class MultimediaItem //reviewed
{

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("src")]
    public string Src { get; set; }

    [OldName("title")]
    public string Title { get; set; }

    [OldName("type")]
    public int? Type { get; set; }

    [OldName("description")]
    public string Description { get; set; }

    [OldName("view")]
    public int? NoOfViews { get; set; }

    [OldName("create_date")]
    public DateTime? CreateDate { get; set; }






    [OldName("lecturer")]
    public int? MultimediaLecturerId { get; set; }
    public MultimediaLecturer MultimediaLecturer { get; set; }
    [OldName("categories")]
    public int? MultimediaCategoryId { get; set; }
    public MultimediaCategory MultimediaCategory  { get; set; }
}