// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia_categories")]
public  class MultimediaCategory //reviewed
{

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    [StringLength(300)]
    public string Name { get; set; }

    public ICollection<MultimediaItem> MultimediaItems { get; set; }

}