// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;
[OldName("multimedia_lecturer")]

public  class MultimediaLecturer//reviewed
{

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int? Id { get; set; }

    [OldName("name")]
    [StringLength(1000)]
    public string Name { get; set; }

    [OldName("status")]
    public short? Status { get; set; }

    [OldName("photo")]
    [StringLength(800)]
    public string Image { get; set; }

    [OldName("descripton")]
    public string Descripton { get; set; }

}