// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("olom_book")]
public  class OlomBook //reviewed
{
    
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Key]
    [OldName("Id")]
    public int? Id { get; set; }

    [OldName("book")]
    public string Name { get; set; }

    [OldName("Field_q")]
    public string MappedColumnName { get; set; }
    public ICollection<OlomChapter> Chapters { get; set; }

}