// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("olom")]
public  class Olom // reviewed
{
    //[OldName("id")]
    public int? Id { get; set; }

    [OldName("matn")]
    public string Matn { get; set; }

    [OldName("new_bab_id")]
    public int BabId { get; set; } // foreign key to OlomBab
    public OlomBab Bab { get; set; }


    [OldName("chapter_id")]
    public int? ChapterNo { get; set; } // foreign key to OlomChapter
    // 
    [OldName("bab_id")]
    public int? BabNo { get; set; } // foreign key to OlomBab

    [OldName("sub_bab_id")]
    public int? SubBabNo { get; set; } // foreign key to OlomSubBab

    [OldName("olom_book_id")]
    public int? OlomBookNo { get; set; } // foreign key to OlomBook
}