// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("olom_chapters")]
public  class OlomChapter //reviewed
{

    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int? Id { get; set; }

    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [OldName("olom_book_id")]
    public int? OlomBookId { get; set; } // foreign key to OlomBook
    public OlomBook OlomBook { get; set; }

    [OldName("chapter_id")]
    public int? ChapterNo { get; set; } // foreign key to Chapter

    public ICollection<OlomBab> OlomBabs { get; set; }
}