// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("olom_bab")]
public  class OlomBab //reviewed
{

    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int? Id { get; set; }
    [OldName("name")]
    public string Name { get; set; } // Name of the Bab

    [OldName("newChapterId")]
    public int? ChapterId { get; set; }
    public OlomChapter Chapter { get; set; }


    [OldName("parent_Id")]
    public int? ParentId { get; set; }
    public OlomBab Parent { get; set; }

    [OldName("bab_id")]
    public int? BabNo { get; set; } 

    [OldName("chapter_id")]
    public int? ChapterNo { get; set; }

    public ICollection<Olom> Oloms { get; set; }

}