// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MosshafContextHandeling.MainModels.NewModels;

public partial class Quran_quran4Context : DbContext
{
    public Quran_quran4Context()
    {
    }

    public Quran_quran4Context(DbContextOptions<Quran_quran4Context> options)
        : base(options)
    {
    }




    public virtual DbSet<Sura> Suras { get; set; }
    public virtual DbSet<Aya> Ayas { get; set; }
    public virtual DbSet<MultimediaCategory> MultimediaCategories { get; set; }
    public virtual DbSet<MultimediaLecturer> MultimediaLecturers { get; set; }
    public virtual DbSet<MultimediaItem> MultimediaItems { get; set; }
    public virtual DbSet<MaanyBook> MaanyBooks { get; set; }
    public virtual DbSet<Maany> Maanies { get; set; }
    public virtual DbSet<Ahkam> Ahkams { get; set; }
    public virtual DbSet<AhkamBook> AhkamBooks { get; set; }
    public virtual DbSet<AsbabNozool> AsbabNozools { get; set; }
    public virtual DbSet<AsbabNozoolBook> AsbabNozoolBooks { get; set; }
    public virtual DbSet<Erab> Erabs { get; set; }
    public virtual DbSet<ErabBook> ErabBooks { get; set; }
    public virtual DbSet<Keraat> Keraats { get; set; }
    public virtual DbSet<Reciter> Reciters { get; set; }
    public virtual DbSet<Moshabeh> Moshabehs { get; set; }
    public virtual DbSet<Tafseer> Tafseers { get; set; }
    public virtual DbSet<TafseerBook> TafseerBooks { get; set; }
    public virtual DbSet<TafseerNabawy> TafseerNabawies { get; set; }
    public virtual DbSet<Tagwed> Tagweds { get; set; }
    public virtual DbSet<Tragem> Tragems { get; set; }
    public virtual DbSet<TragemBook> TragemBooks { get; set; }
    public virtual DbSet<OlomBook> OlomBooks { get; set; }
    public virtual DbSet<OlomChapter> OlomChapters { get; set; }
    public virtual DbSet<OlomBab> OlomBabs { get; set; }
    public virtual DbSet<Olom> Oloms { get; set; }
    public virtual DbSet<EgazBook> EgazBooks { get; set; }
    public virtual DbSet<EgazChapter> EgazChapters { get; set; }
    public virtual DbSet<EgazBab> EgazBabs { get; set; }
    public virtual DbSet<Egaz> Egazs { get; set; }
    public virtual DbSet<MogamBook> MogamBooks { get; set; }
    public virtual DbSet<MogamChapter> MogamChapters { get; set; }
    public virtual DbSet<MogamBab> MogamBabs { get; set; }
    public virtual DbSet<Mogam> Mogams { get; set; }
    public virtual DbSet<Radio> Radios { get; set; }
    /// <summary>
    /// ////////new models
    /// </summary>
    public virtual DbSet<Tafser> Tafsers { get; set; }
    public virtual DbSet<Ahhkam> Ahhkams { get; set; }



    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Server=URANUS\\DEV;Database=MoshafShariefDb;User Id=ils;Password=ils@123;MultipleActiveResultSets=true;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}