// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("reciters")]
//[Keyless]
public  class Reciter //reviewed
{

    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("ReciterID")]
    public int Id { get; set; }

    [Required]
    [OldName("ar_name")]
    public string ArName { get; set; }

    [Required]
    [OldName("en_name")]
    public string EnName { get; set; }

    [Required]
    [OldName("folder")]
    public string FolderName { get; set; }

    [OldName("karat")]
    public int KeraatId { get; set; } 
    public Keraat Keraat { get; set; }
}