// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Keyless]
[OldName("sura")]
public class Sura //reviewed
{
    //public int FakeId { get; set; }

    [OldName("SuraNo")]
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [OldName("SuraName")]
    [StringLength(50)]
    public string Name { get; set; }

    [OldName("Verses")]
    public int? NoOfVerses { get; set; }

    [OldName("Type")]
    [Required]
    [StringLength(100)]
    public string Type { get; set; }

    [Required]
    [OldName("title")]
    [StringLength(100)]
    public string Title { get; set; }

    // الحاجات الي على جنب السوره اليمين 
    [Required]
    [OldName("sabb_tasmia")]
    public string SabbTasmia { get; set; }

    [Required]
    [OldName("ta3reef")]
    public string Taareef { get; set; }

    [Required]
    [OldName("mwadee3")]
    public string Mwadee { get; set; }

    [Required]
    [OldName("sabb_nzol")]
    public string SabbNzol { get; set; }

    [Required]
    [OldName("fadl")]
    public string Fadl { get; set; } // TODO: For what?

    public List<Aya> Ayas { get; set; }
}
