// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Keyless]
//[Table("tafseer", Schema = "quran_quran2")]
[OldName("tafseer")]
public  class Tafseer
{ 
    //[OldName("id")]
    public int? Id { get; set; }

    [OldName("QuranID")]
    public int? AyaId { get; set; }
    public Aya Aya { get; set; }

    [OldName("elgalalen")]
    public string Elgalalen { get; set; }//---

    [OldName("ibnkathir")]
    public string Ibnkathir { get; set; }//---

    [OldName("mo7et")]
    public string Mohet { get; set; }//---

    [OldName("kortoby")]
    public string Kortoby { get; set; }//---

    [OldName("kadeer")]
    public string Kadeer { get; set; }//---

    [OldName("elmoysar")]
    public string Elmoysar { get; set; }//---

    [OldName("ezzsalam")]
    public string EzzSalam { get; set; }//---

    [OldName("elwaseet")]
    public string Elwaseet { get; set; }//---

    [OldName("baedawy")]
    public string Baedawy { get; set; }//---

    [OldName("aysar")]
    public string Aysar { get; set; }//---

    [OldName("ba3awy")]
    public string Baaawy { get; set; }//---

    [OldName("nasafy")]
    public string Nasafy { get; set; }//---

    [OldName("montkab")]
    public string Montkhab { get; set; }//---

    [OldName("mawrdy")]
    public string Mawrdy { get; set; }//---

    [OldName("bnothemen")]
    public string Bnothemen { get; set; }//---

    [OldName("mara7")]
    public string Mara7 { get; set; }//---

    [OldName("tabary1")]
    public string Tabary { get; set; }//---

    [OldName("sa3dy1")]
    public string Saady1 { get; set; }//---

    [OldName("baseet")]
    public string Baseet { get; set; }//---

    [OldName("hatem1")]
    public string Hatem { get; set; }//---

    [OldName("arafa")]
    public string Arafa { get; set; }//---

    [OldName("maser")]
    public string ZadAlMaser { get; set; }//---

    [OldName("zahra")]
    public string Zahra { get; set; }//---

    [OldName("moqatel")]
    public string Moqatel { get; set; }//---

    [OldName("dorar")]
    public string Dorar { get; set; }//---

    [OldName("mafateh1")]
    public string Mafateh { get; set; }//---

    [OldName("wageez")]
    public string MoharrerWageez { get; set; }//---

    [OldName("mason")]
    public string DorAlMason { get; set; }//---

    [OldName("bian")]
    public string FatthBian { get; set; }//---

    [OldName("mojahed")]
    public string Mojahed { get; set; }//---

    [OldName("sofian")]
    public string SofianAlThawry { get; set; }//---

    [OldName("tasheel")]
    public string Tasheel { get; set; }//---

    [OldName("razzaq")]
    public string RazzaqSanaany { get; set; }//---

    [OldName("eegy")]
    public string GameeBianEegy { get; set; }//---

    [OldName("mara3i")]
    public string Maraghi { get; set; }//---

    [OldName("3azb")]
    public string Aazb { get; set; }//---

    [OldName("safwat1")]
    public string Safwat { get; set; }//---

    [OldName("adwa1")]
    public string Adwa { get; set; }//---

    [OldName("kashaf2")]
    public string KashafZamakhshary { get; set; }//---

    [OldName("wa7dy1")]
    public string WageezWahdy { get; set; }//---

    [OldName("sha3rawy_new")]
    public string ShaarawyNew { get; set; }//---

    [OldName("dor1")]
    public string Dor { get; set; }//---

    [OldName("saood1")]
    public string ErshadSaood { get; set; }//---

    [OldName("many2")]
    public string Many { get; set; }//---

    [OldName("qasmi1")]
    public string MahasenQasmi { get; set; }//---

    [OldName("manar1")]
    public string Manar { get; set; }//---

    [OldName("ta7reer1")]
    public string Tahreer { get; set; }//---

    [OldName("qatan1")]
    public string Qatan { get; set; }//---

}