// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

//[Table("tafseer_book", Schema = "quran_quran2")]
[OldName("tafseer_book")]
public  class TafseerBook
{
    //[Key]
    //[OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("book")]
    public string Name { get; set; }


    [Required]
    [OldName("details")]
    public string Details { get; set; }

    public  ICollection<Tafser> Tafsers { get; set; } 
}