// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;


[OldName("tagwed")]
public class Tagwed
{
    public int Id { get; set; }


    [OldName("AyaId")]
    public int AyaId { get; set; }
    public Aya Aya { get; set; }

    [OldName("GVerse")]
    public string Gverse { get; set; }
    [Required]
    [OldName("tagwed")]
    public string Tagweed { get; set; }

    [OldName("tagen")]
    public string Tagen { get; set; }
}