// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MosshafContextHandeling.Helpers;

namespace MosshafContextHandeling.MainModels.NewModels;

[OldName("tragem_book")]
public  class TragemBook
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("book")]
    public string Name { get; set; }

}